#!/usr/bin/env python3
"""
Train YOLO model for SLD symbol detection.

Prerequisites:
    pip install ultralytics pillow

Dataset structure (generated by generate_synthetic.py):
    data/
    ├── synthetic/
    │   ├── images/
    │   │   ├── train/
    │   │   └── val/
    │   └── labels/   (YOLO format)

Usage:
    python scripts/train_yolo.py --data data/synthetic --epochs 100 --batch 16

To generate images from ground truth:
    python scripts/generate_synthetic.py  # creates JSON ground truth
    # Then render those JSONs to PNG images using the renderer
"""
import argparse
import json
import shutil
import uuid
from pathlib import Path
from typing import BinaryIO

def convert_gt_to_yolo_dataset(
    gt_dir: Path,
    output_dir: Path,
    split: tuple[float, float, float] = (0.8, 0.1, 0.1),
    render_images: bool = True,
):
    """Convert synthetic ground truth JSON files to YOLO-format dataset.

    Args:
        gt_dir: Directory containing *_gt.json files
        output_dir: Root output directory
        split: (train, val, test) ratios
        render_images: If True, renders synthetic SLD images from JSON.
                      If False, only creates label files.
    """
    assert sum(split) == 1.0, "Split ratios must sum to 1.0"
    train_ratio, val_ratio, test_ratio = split

    # Component type to class ID mapping (must match SymbolDetector.COMPONENT_CLASSES)
    TYPE_TO_ID = {
        "transformer_2w": 0, "circuit_breaker": 1, "disconnect_switch": 2,
        "busbar": 3, "current_transformer": 4, "voltage_transformer": 5,
        "reactor": 6, "capacitor": 7, "feeder_terminal": 8, "ground": 9,
        "surge_arrester": 10, "fuse": 11, "load_break_switch": 12,
        "transformer_3w": 13, "generator": 14, "motor": 15, "jumper": 16,
        "unknown": 17,
    }
    IMG_W, IMG_H = 1200, 800  # Canvas size

    gt_files = sorted(gt_dir.glob("*_gt.json"))
    if not gt_files:
        print(f"No *_gt.json files found in {gt_dir}")
        return

    n = len(gt_files)
    n_train = int(n * train_ratio)
    n_val = int(n * val_ratio)

    splits = {
        "train": gt_files[:n_train],
        "val": gt_files[n_train:n_train + n_val],
        "test": gt_files[n_train + n_val:],
    }

    for split_name, files in splits.items():
        img_out = output_dir / "images" / split_name
        label_out = output_dir / "labels" / split_name
        img_out.mkdir(parents=True, exist_ok=True)
        label_out.mkdir(parents=True, exist_ok=True)

        for gt_path in files:
            with open(gt_path) as f:
                gt = json.load(f)

            # Write YOLO label file
            label_file = label_out / f"{gt_path.stem}.txt"
            with open(label_file, "w") as lf:
                for comp in gt.get("components", []):
                    ctype = comp.get("component_type", "unknown")
                    class_id = TYPE_TO_ID.get(ctype, TYPE_TO_ID["unknown"])

                    pos = comp.get("position", {})
                    bbox = comp.get("bbox", {})
                    # Use bbox if available, else derive from position
                    if bbox:
                        x_min, y_min = bbox.get("x_min", pos.get("x", 0)), bbox.get("y_min", pos.get("y", 0))
                        w = bbox.get("x_max", x_min + 30) - x_min
                        h = bbox.get("y_max", y_min + 20) - y_min
                    else:
                        x_min = pos.get("x", 0) - 15
                        y_min = pos.get("y", 0) - 10
                        w, h = 30, 20

                    # Convert to YOLO normalized format (center_x, center_y, w, h)
                    cx = (x_min + w / 2) / IMG_W
                    cy = (y_min + h / 2) / IMG_H
                    nw = w / IMG_W
                    nh = h / IMG_H
                    lf.write(f"{class_id} {cx:.6f} {cy:.6f} {nw:.6f} {nh:.6f}\n")

            # Render synthetic image from JSON
            if render_images:
                try:
                    from PIL import Image, ImageDraw, ImageFont
                except ImportError:
                    print("Pillow not available, skipping image rendering")
                    render_images = False
                    continue

                img = Image.new("RGB", (IMG_W, IMG_H), color=(255, 255, 255))
                draw = ImageDraw.Draw(img)

                symbol_colors = {
                    "transformer_2w": (245, 158, 11), "transformer_3w": (249, 115, 22),
                    "busbar": (59, 130, 246), "circuit_breaker": (34, 197, 94),
                    "disconnect_switch": (6, 182, 212), "load_break_switch": (139, 92, 246),
                    "current_transformer": (236, 72, 153), "voltage_transformer": (217, 70, 239),
                    "reactor": (132, 204, 22), "capacitor": (163, 230, 53),
                    "generator": (239, 68, 68), "feeder_terminal": (100, 116, 139),
                    "ground": (107, 114, 128), "surge_arrester": (244, 63, 94),
                    "fuse": (168, 85, 247), "unknown": (71, 85, 105),
                }

                for comp in gt.get("components", []):
                    x, y = comp.get("position", {}).get("x", 0), comp.get("position", {}).get("y", 0)
                    ctype = comp.get("component_type", "unknown")
                    color = symbol_colors.get(ctype, symbol_colors["unknown"])

                    if ctype == "busbar":
                        draw.rectangle([x - 40, y - 6, x + 40, y + 6], fill=color, outline=(0, 0, 0))
                    elif ctype.startswith("transformer"):
                        draw.ellipse([x - 14, y - 14, x + 14, y + 14], fill=color, outline=(0, 0, 0))
                    elif ctype == "circuit_breaker":
                        draw.rectangle([x - 11, y - 11, x + 11, y + 11], fill=color, outline=(0, 0, 0))
                    else:
                        draw.ellipse([x - 9, y - 9, x + 9, y + 9], fill=color, outline=(0, 0, 0))

                    if comp.get("label"):
                        draw.text((x + 12, y - 6), comp["label"], fill=(0, 0, 0))

                img_path = img_out / f"{gt_path.stem}.png"
                img.save(img_path)

    # Create dataset YAML for YOLO training
    yaml_content = f"""path: {output_dir.resolve()}
train: images/train
val: images/val
test: images/test

names:
  0: transformer_2w
  1: circuit_breaker
  2: disconnect_switch
  3: busbar
  4: current_transformer
  5: voltage_transformer
  6: reactor
  7: capacitor
  8: feeder_terminal
  9: ground
  10: surge_arrester
  11: fuse
  12: load_break_switch
  13: transformer_3w
  14: generator
  15: motor
  16: jumper
  17: unknown
"""
    (output_dir / "dataset.yaml").write_text(yaml_content)
    print(f"Dataset prepared at: {output_dir}")
    print(f"  Train: {len(splits['train'])} | Val: {len(splits['val'])} | Test: {len(splits['test'])}")
    print(f"  Config: {output_dir / 'dataset.yaml'}")


def train_yolo(
    data_yaml: str,
    model_size: str = "yolov8m",
    epochs: int = 100,
    batch_size: int = 16,
    img_size: int = 640,
    device: str = "cuda",
    project: str = "runs/detect",
    name: str = "sld_train",
):
    """Train YOLO model. Requires ultralytics package."""
    try:
        from ultralytics import YOLO
    except ImportError:
        print("ERROR: ultralytics not installed. Run: pip install ultralytics")
        return

    print(f"Starting YOLO training: {model_size}, {epochs} epochs, batch={batch_size}")
    print(f"Data config: {data_yaml}")
    print(f"Device: {device}")

    model = YOLO(f"{model_size}.pt")  # Load pretrained model
    results = model.train(
        data=data_yaml,
        epochs=epochs,
        batch=batch_size,
        imgsz=img_size,
        device=device,
        project=project,
        name=name,
        patience=20,        # Early stopping patience
        save=True,
        plots=True,
        val=True,
        amp=True,           # Mixed precision
        lr0=0.01,
        lrf=0.01,
        momentum=0.937,
        weight_decay=0.0005,
        warmup_epochs=3,
        close_mosaic=10,
    )

    best_path = f"{project}/{name}/weights/best.pt"
    print(f"\nTraining complete. Best model: {best_path}")
    return best_path


def main():
    ap = argparse.ArgumentParser(description="Train YOLO on SLD data")
    ap.add_argument("--data", default="data/synthetic", help="Ground truth JSON directory")
    ap.add_argument("--output", default="data/yolo_dataset", help="YOLO dataset output dir")
    ap.add_argument("--epochs", type=int, default=100)
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--model", default="yolov8m", choices=["yolov8n", "yolov8s", "yolov8m", "yolov8l", "yolov8x"])
    ap.add_argument("--img-size", type=int, default=640)
    ap.add_argument("--device", default="cuda", help="cuda or cpu")
    ap.add_argument("--prepare-only", action="store_true", help="Only prepare dataset, don't train")
    ap.add_argument("--model-path", help="Path to existing model.pt (skip preparation)")
    args = ap.parse_args()

    data_path = Path(args.data)
    output_path = Path(args.output)

    if not args.model_path:
        print("=== Step 1: Preparing YOLO dataset ===")
        convert_gt_to_yolo_dataset(data_path, output_path)
        if args.prepare_only:
            return
        data_yaml = str(output_path / "dataset.yaml")
    else:
        data_yaml = str(Path(args.model_path).parent.parent / "dataset.yaml")
        if not Path(data_yaml).exists():
            print(f"dataset.yaml not found at {data_yaml}")
            return

    print(f"\n=== Step 2: Training YOLO ({args.model}) ===")
    best = train_yolo(
        data_yaml=data_yaml,
        model_size=args.model,
        epochs=args.epochs,
        batch_size=args.batch,
        img_size=args.img_size,
        device=args.device,
    )
    print(f"\nDone. Model saved to: {best}")


if __name__ == "__main__":
    main()
